#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import subprocess
import os
import sys
import datetime
from datetime import timedelta, date

start = "2017-11-16"
stop = "2018-01-16"
delta = 2

start_date = datetime.datetime.strptime('%s' % start, '%Y-%m-%d')
end_date = datetime.datetime.strptime('%s' % stop, '%Y-%m-%d')

d = start_date
while d <= end_date:
    print d.strftime("%Y-%m-%d")
    d += datetime.timedelta(delta)
