server:
<<<<<<< HEAD
    address:
    username: statuser 
    password: statuser

filter:
    filter_name:
    filter_value:

=======
    address: http://
    username: 
    password: 
filter:
    filter_name: projectCategory.name
    filter_value: 
>>>>>>> 4b867daed622e54771f0acd016736ee8d382974a

date:
    start:
    stop:
    delta:
<<<<<<< HEAD

jql:
=======
>>>>>>> 4b867daed622e54771f0acd016736ee8d382974a
